GeradorDeFolha/Controllers/PainelController.cs
using Microsoft.AspNetCore.Mvc;
using GeradorDeFolha.Filters;
using GeradorDeFolha.Models;
using GeradorDeFolha.Repositorio;
using System.Text;

namespace GeradorDeFolha.Controllers
{
    [UsuarioVerificacaoPerfil]
    public class PainelController : Controller
    {
        private readonly ICadastroRepositorio _cadastroFuncionarioRepositorio;

        public PainelController(
            ICadastroRepositorio cadastroRepositorio
        )
        {
            _cadastroFuncionarioRepositorio = cadastroRepositorio;
        }

        //CadastroModel teste = new CadastroModel();
        public IActionResult Index()
        {
            List<CadastroModel> Funcionarios =
                _cadastroFuncionarioRepositorio.BuscarTodos();
            return View(Funcionarios);
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            CadastroModel funcionario = _cadastroFuncionarioRepositorio.ListarPorId(id);
            return View(funcionario);
        }

        public IActionResult GerarHolerite(int id)
        {
            CadastroModel funcionario = _cadastroFuncionarioRepositorio.ListarPorId(id);
            return View(funcionario);
        }

        public IActionResult Excluir(int id)
        {
            CadastroModel colaborador = _cadastroFuncionarioRepositorio.ListarPorId(id);
            return View(colaborador);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _cadastroFuncionarioRepositorio.Apagar(id);

                if (apagado) TempData["MensagemSucesso"] = "Usuário apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos apagar seu usuário, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu usuário, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Cadastro(CadastroModel cadastro)
        {
            //------------------------------//
            try
            {
                if (ModelState.IsValid)
                {
                    Console.WriteLine("Cadastro" + cadastro);
                    string senha = cadastro.senha;
                    string encodedStr = Convert.ToBase64String(Encoding.UTF8.GetBytes(senha));
                    cadastro.senha = encodedStr;
                    string sexo = cadastro.Sexo;
                    _cadastroFuncionarioRepositorio.Adicionar(cadastro);
                    cadastro = _cadastroFuncionarioRepositorio.Adicionar(cadastro);
                    TempData["MensagemSucesso"] = "Colaborador cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(cadastro);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu colaborador, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(CadastroModel cadastro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Console.WriteLine("Cadastro" + cadastro);
                    string senha = cadastro.senha;
                    string encodedStr = Convert.ToBase64String(Encoding.UTF8.GetBytes(senha));
                    cadastro.senha = encodedStr;
                    _cadastroFuncionarioRepositorio.Atualizar(cadastro);
                    cadastro = _cadastroFuncionarioRepositorio.Atualizar(cadastro);
                    TempData["MensagemSucesso"] = "Colaborador alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(cadastro);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu colaborador, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult GerarHolerite(CadastroModel cadastro)
        {
            if (
                string.IsNullOrEmpty(cadastro.nome)
                || string.IsNullOrEmpty(cadastro.senha)
                || string.IsNullOrEmpty(cadastro.email)
            )
            {
                ModelState.AddModelError(
                    "",
                    "Por favor, preencha todos os campos antes de cadastrar."
                );
                return View(cadastro);
            }
            Console.WriteLine("Cadastro" + cadastro);
            _cadastroFuncionarioRepositorio.Atualizar(cadastro);
            return RedirectToAction("Index");
        }
    }
}

GeradorDeFolha/Views/Painel/Cadastro.cshtml
@using GeradorDeFolha.Enums;
@model CadastroModel
@{
    ViewData["Title"] = "Cadastro Colaborador";
    Layout = "_LayoutMain";
}


<main id="main" class="main">
    <div class="text-center">
         <div class="pagetitle">
            <h1>Cadastro Colaborador</h1>
         </div>
    </div>
    @Html.ValidationSummary()
    <section class="section">
        <div class="row">
            <div class="texte-center">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dados Cadastrais</h5>
                        <form asp-controller="PainelController" asp-action="Criar" method="post">
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Nome Completo</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="nome" class="form-control">
                                    @Html.ValidationMessageFor(x => x.nome)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputEmail" class="col-sm-2 col-form-label">E-mail</label>
                                <div class="col-sm-10">
                                    <input type="email" asp-for="email" class="form-control">
                                    @Html.ValidationMessageFor(x => x.email)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">CPF</label>
                                <div class="col-sm-10">
                                    <input type="text" id="cpfInput" asp-for="cpf" class="form-control" maxlength="11">
                                    @Html.ValidationMessageFor(x => x.cpf)
                                </div>
                            </div>
                            <fieldset class="row mb-3">
                                <legend class="col-form-label col-sm-2 pt-0">Sexo</legend>
                                <div class="col-sm-10">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="Sexo" id="gridRadios1" value="M" checked>
                                        <label class="form-check-label" for="gridRadios1">Masculino</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="Sexo" id="gridRadios2" value="F">
                                        <label class="form-check-label" for="gridRadios2">Feminino</label>
                                    </div>
                                </div>
                            </fieldset>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Perfil</label>
                                <div class="col-sm-10">
                                    <select asp-for="Perfil" class="form-control">
                                        <option value="0">Selecione o Tipo de Conta</option>
                                        <option value="@PerfilEnum.Master">Master</option>
                                        <option value="@PerfilEnum.Comum">Comum</option>
                                        @Html.ValidationMessageFor(x => x.Perfil)
                                        <!-- Adicione mais opções conforme necessário -->
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputDate" class="col-sm-2 col-form-label">Data da Admissão</label>
                                <div class="col-sm-10">
                                    <input type="date" asp-for="AdmissaoData" class="form-control">
                                    @Html.ValidationMessageFor(x => x.AdmissaoData)
                                </div>
                            </div>
                            <!-- Validação de senha -->
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Criar Senha</label>
                                <div class="col-sm-10">
                                    <input type="password" asp-for="senha" class="form-control" id="senha">
                                    @Html.ValidationMessageFor(x => x.senha)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Repita a Senha</label>
                                <div class="col-sm-10">
                                    <input type="password" asp-for="ConfirmarSenha" class="form-control" id="confirmarSenha">
                                    @Html.ValidationMessageFor(x => x.ConfirmarSenha)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Cargo</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="cargo" class="form-control">
                                    @Html.ValidationMessageFor(x => x.cargo)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Salário</label>
                                <div class="col-sm-10">
                                    <input type="number" asp-for="SalarioB" class="form-control">
                                    @Html.ValidationMessageFor(x => x.SalarioB)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="d-flex justify-content-between">
                                    <a role="button" class="btn btn-secondary" asp-controller="Painel" asp-action="Index"> Voltar</a>
                                    <button type="submit" class="btn btn-success" asp-controller="Painel" asp-action="Cadastro">Cadastrar</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

GeradorDeFolha/Views/Painel/Editar.cshtml
@using GeradorDeFolha.Enums;
@model CadastroModel
@{
    ViewData["Title"] = "Editar Colaborador";
    Layout = "_LayoutMain";
}


<main id="main" class="main">
    <div class="text-center">
        <div class="pagetitle">
            <h1>Atualizar Colaborador</h1>
        </div>
    </div>
    @Html.ValidationSummary()
    <section class="section">
        <div class="row">
            <div class="texte-center">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dados Cadastrais</h5>
                        <form asp-controller="PainelController" asp-action="Editar" method="post">
                            <input type="hidden" asp-for="Id" />
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Nome Completo</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="nome" class="form-control">
                                    @Html.ValidationMessageFor(x => x.nome)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputEmail" class="col-sm-2 col-form-label">E-mail</label>
                                <div class="col-sm-10">
                                    <input type="email" asp-for="email" class="form-control">
                                    @Html.ValidationMessageFor(x => x.email)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">CPF</label>
                                <div class="col-sm-10">
                                    <input type="text" id="cpfInput" asp-for="cpf" class="form-control" maxlength="14">
                                    @Html.ValidationMessageFor(x => x.cpf)
                                </div>
                            </div>
                            <fieldset class="row mb-3">
                                <legend class="col-form-label col-sm-2 pt-0">Sexo</legend>
                                <div class="col-sm-10">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="Sexo" id="gridRadios1" value="Masculino" checked>
                                        <label class="form-check-label" for="gridRadios1">Masculino</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="Sexo" id="gridRadios2" value="Feminino">
                                        <label class="form-check-label" for="gridRadios2">Feminino</label>
                                    </div>
                                </div>
                            </fieldset>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Perfil</label>
                                <div class="col-sm-10">
                                    <select asp-for="Perfil" class="form-control">
                                        <option value="0">Selecione o Perfil de Acessso</option>
                                        <option value="@PerfilEnum.Master">Master</option>
                                        <option value="@PerfilEnum.Comum">Comum</option>
                                        @Html.ValidationMessageFor(x => x.Perfil)
                                        <!-- Adicione mais opções conforme necessário -->
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputDate" class="col-sm-2 col-form-label">Data da Admissão</label>
                                <div class="col-sm-10">
                                    <input type="date" asp-for="AdmissaoData" class="form-control">
                                    @Html.ValidationMessageFor(x => x.AdmissaoData)
                                </div>
                            </div>
                            
                            <!-- Validação de senha -->
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Criar Senha</label>
                                <div class="col-sm-10">
                                    <input type="password" asp-for="senha" class="form-control" id="senha">
                                    @Html.ValidationMessageFor(x => x.senha)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Repita a Senha</label>
                                <div class="col-sm-10">
                                    <input type="password" asp-for="ConfirmarSenha" class="form-control" id="confirmarSenha">
                                    @Html.ValidationMessageFor(x => x.ConfirmarSenha)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Cargo</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="cargo" class="form-control">
                                    @Html.ValidationMessageFor(x => x.cargo)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Salário</label>
                                <div class="col-sm-10">
                                    <input type="number" asp-for="SalarioB" class="form-control">
                                    @Html.ValidationMessageFor(x => x.SalarioB)
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="d-flex justify-content-between">
                                    <a role="button" class="btn btn-secondary" asp-controller="Painel" asp-action="Index"> Voltar</a>
                                    <button type="submit" class="btn btn-success" asp-controller="Painel" asp-action="Editar">Atualiazar</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>

GeradorDeFolha/Views/Painel/Excluir.cshtml
@model CadastroModel
@{
    ViewData["Title"] = "Confirmação apagar colaborador";
     Layout = "_LayoutMain";
}

<main id="main" class="main">
    <section class="section">
        <div class="text-center">
            <div class="text-center">
                <h2>Realmente deseja apagar o usuário (@Model.nome)</h2>
            </div>
            </br>
            <a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Painel" role="button">Cancelar exclusão</a>
            <a class="btn btn-danger btn-block" asp-action="Apagar" asp-controller="Painel" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>
        </div>
    </section>
</main>

GeradorDeFolha/Views/Painel/GerarHolerite.cshtml
@model CadastroModel
@{
    ViewData["Title"] = "Gerador de Holerites";
    Layout = "_LayoutMain";
}

<main id="main" class="main">
    <div class="text-center">
        <div class="pagetitle">
            <h1>Gerador de Holerite</h1>
        </div>
    </div>
    @Html.ValidationSummary()
    <section class="section">
        <div class="row">
            <div class="texte-center">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Informações da Folha</h5>
                        <form asp-controller="PainelController" asp-action="GerarHolerite" method="post">
                            <input type="hidden" asp-for="Id" />
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Nome Completo</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="nome" class="form-control">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputDate" class="col-sm-2 col-form-label">Data da Admissão</label>
                                <div class="col-sm-10">
                                    <input type="date" asp-for="AdmissaoData" class="form-control">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">CPF</label>
                                <div class="col-sm-10">
                                    <input type="text" id="cpfInput" asp-for="cpf" class="form-control" maxlength="14">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Cargo</label>
                                <div class="col-sm-10">
                                    <select asp-for="cargo" class="form-control">
                                        <option value="">Selecione o Cargo</option>
                                        <option value="Desenvolvedor Trainee">Desenvolvedor Trainee</option>
                                        <option value="Desenvolvedor Júnior">Desenvolvedor Júnior</option>
                                        <option value="Desenvolvedor Pleno">Desenvolvedor Pleno</option>
                                        <option value="Desenvolvedor Sênior">Desenvolvedor Sênior</option>
                                        <!-- Adicione mais opções conforme necessário -->
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Salário</label>
                                <div class="col-sm-10">
                                    <input type="number" asp-for="SalarioB" class="form-control">
                                </div>
                            </div>
                            <!-- Adicione os campos restantes do holerite -->
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Horas Extras</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="HorasExtras" class="form-control"-->
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Desconto INSS</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="DescontoINSS" class="form-control"-->
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Desconto IR</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="DescontoIR" class="form-control"-->
                                </div>
                            </div>
                            <!-- Calcule e mostre os campos Total de Vencimentos, Total de Descontos e Salário Líquido -->
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Total de Vencimentos</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="TotalVencimentos" class="form-control" readonly-->
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Total de Descontos</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="TotalDescontos" class="form-control" readonly-->
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Salário Líquido</label>
                                <div class="col-sm-10">
                                    <!--input type="number" asp-for="SalarioLiquido" class="form-control" readonly-->
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="d-flex justify-content-between">
                                    <a role="button" class="btn btn-secondary" asp-controller="Painel" asp-action="Index"> Voltar</a>
                                    <button type="submit" class="btn btn-success" asp-controller="Painel" asp-action="GerarHolerite">Gerar Holerite</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>

GeradorDeFolha/Views/Painel/Index.cshtml
@model List<CadastroModel>
@{
    ViewData["Title"] = "Painel de Controle";
    Layout = "_LayoutMain";
}

<style>
    .table {
        background-color: #f0fff0; /* Verde claro para a tabela */
    }

    th, td {
        color: #008000; /* Verde escuro para texto */
    }

    .btn-success {
        background-color: #008000; /* Verde escuro para botões de sucesso */
        border-color: #008000;
    }

        .btn-success:hover {
            background-color: #006400; /* Verde mais escuro quando hover */
            border-color: #006400;
        }

    .navbar {
        background-color: #f0fff0; /* Verde claro para a barra de navegação */
    }
</style>

<main id="main" class="main">

    <section class="section">
        <div class="text-center">
            <div class="pagetitle">
                <h1 class="display-4">Lista de Colaboradores</h1>
            </div>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a aria-current="page" class="btn btn-success" role="button" asp-controller="Painel" asp-action="Cadastro">Cadastrar Colaborador</a>
                            </li>
                        </ul>
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                            <button class="btn btn-success" type="submit">Buscar</button>
                        </form>
                    </div>
                </div>
            </nav>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Admissão</th>
                        <th scope="col">Cargo</th>
                        <th scope="col">Salário</th>
                        <th scope="col">Perfil</th>
                        <th scope="col">Opções</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (CadastroModel funcionario in Model)
                        {
                            <tr>
                                <th scope="row">@funcionario.Id</th>
                                <td>@funcionario.nome</td>
                                <td>@funcionario.email</td>
                                <td>@funcionario.AdmissaoData</td>
                                <td>@funcionario.cargo</td>
                                <td>@funcionario.SalarioB.ToString("C")</td>
                                <td>@(funcionario.Perfil == GeradorDeFolha.Enums.PerfilEnum.Master ? "Master" : "Padrão")</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Exemplo básico">
                                        <a role="button" class="btn btn-success" asp-route-id="@funcionario.Id" asp-controller="Painel" asp-action="Editar">Atualizar</a>
                                        <a role="button" class="btn btn-info" asp-route-id="@funcionario.Id" asp-controller="Painel" asp-action="GerarHolerite">Criar Holerite</a>
                                        <a role="button" class="btn btn-danger" asp-route-id="@funcionario.Id" asp-controller="Painel" asp-action="Excluir">Excluir</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr class="odd"><td valign="top" colspan="5">Nenhum funcionario encontrado</td></tr>
                    }
                </tbody>
            </table>
            <div class="d-flex justify-content-between">
                <a role="button" class="btn btn-secondary" asp-controller="Home" asp-action="Index"> Voltar</a>
            </div>
        </div>
    </section>
</main>